set XCStrings model
superarts/XStringCatalog pull request #14
Opened 2023-12-19 01:51 UTC by Uni-boy

- XCString model implemented

## Related issue(s)

- #1

2023-12-19 03:38 UTC, superarts commented
@Uni-boy is your PR ready for review please?

2023-12-19 07:21 UTC, Uni-boy commented
Yeah my PR is ready.

2023-12-19 07:28 UTC, superarts requested changes
Why would we just add some passive data models without using them?

2023-12-19 07:28 UTC, superarts commented on StringCatalogEnum/Sources/StringCatalogEnum/model.swift
> +*/
Is the dead code still useful? Do we want to remove it?

2023-12-19 07:28 UTC, superarts commented on StringCatalogEnum/Sources/StringCatalogEnum/model.swift
> +struct XCStrings: Decodable {
In https://github.com/superarts/XStringCatalog/issues/1, we listed several possible formats. Do we need to document the `struct`s here with sample JSON?

2023-12-19 07:28 UTC, superarts commented on StringCatalogEnum/Sources/StringCatalogEnum/model.swift
> +struct StringInfo: Decodable {
Is it the best practice to put all `struct`s in the same source file?

2023-12-20 01:35 UTC, superarts requested changes
Again, these structs should be consumed. Please check my previous comments: https://github.com/superarts/XStringCatalog/pull/14#pullrequestreview-1788247590

2023-12-28 11:16 UTC, superarts commented
@Uni-boy if you don't have any plan to update this PR, please feel free to close it. Thank you.

2023-12-31 05:17 UTC, Uni-boy commented
I finalized the model and all tests passed.

2024-01-01 15:58 UTC, superarts commented
> I finalized the model and all tests passed.

Please merge from `master` and resolve conflicts.

More importantly, when I said "these structs should be consumed", I meant the `structs` you created should replace codes like `let strings = json["strings"] as? [String: Any]` in `main.swift`. What do you think the codebase can benefit from some data models that are not used anywhere?

2024-01-03 00:28 UTC, Uni-boy commented
> > I finalized the model and all tests passed.
> 
> Please merge from `master` and resolve conflicts.
> 
> More importantly, when I said "these structs should be consumed", I meant the `structs` you created should replace codes like `let strings = json["strings"] as? [String: Any]` in `main.swift`. What do you think the codebase can benefit from some data models that are not used anywhere?

I applied the model to main.swift and solved the TODO in StringEnumHelper.swift

2024-01-03 07:21 UTC, superarts commented on StringCatalogEnum/Sources/StringCatalogEnum/main.swift
> +        let strings = try decoder.decode(Localizations.self, from: data)
This is a step to the right direction 👍

2024-01-04 20:10 UTC, superarts requested changes
Please address the obvious issues I pointed out, but my PR review is not finished yet. I'll add another review soon.

2024-01-04 20:10 UTC, superarts commented on StringCatalogEnum/Sources/StringCatalogEnum/main.swift
> +        // }
As a general, don't include dead code in your PRs. If you really have a good reason, add a `TODO` or something to explain why the dead code would be needed.

2024-01-04 20:10 UTC, superarts commented on StringCatalogEnum/Sources/StringCatalogEnum/model.swift
This file can be deleted because you are creating models in the library module.

2024-01-04 20:10 UTC, superarts commented on StringCatalogEnum/Sources/StringCatalogEnum/model.swift
> -     let strings: [Strsing: String]
my bad lol

2024-01-04 20:10 UTC, superarts commented on StringCatalogEnum/Sources/StringCatalogEnumLibrary/Models.swift
> +// struct Variations: Decodable {
These are dead codes too but I'll need to further look into it.

2024-01-05 03:44 UTC, superarts requested changes
Almost there! Just a few minor suggestions.

2024-01-05 03:44 UTC, superarts commented on StringCatalogEnum/Sources/StringCatalogEnumLibrary/StringEnumHelper.swift
>              // TODO: extract `localizations.en.stringUnit.value` and add in comments as inline documents
Since it's already implemented, we can remove this `TODO` now.

2024-01-05 03:44 UTC, superarts commented on StringCatalogEnum/Sources/StringCatalogEnumLibrary/StringEnumHelper.swift
> +                        localizationComments.append("    /// \(languageCode): \(value)")
```suggestion
                        localizationComments.append("    /// '\(languageCode)': \"\(value)\"")
```

2024-01-05 03:44 UTC, superarts commented on StringCatalogEnum/Sources/StringCatalogEnumLibrary/StringEnumHelper.swift
> +
```suggestion
```

2024-01-05 04:49 UTC, superarts requested changes
Please address this: https://github.com/superarts/XStringCatalog/pull/14#discussion_r1442468230

And added some other suggestions regarding unit tests. Sorry I forgot them in my previous review.

2024-01-05 04:49 UTC, superarts commented on StringCatalogEnum/Tests/StringCatalogEnumTests/StringCatalogEnumTests.swift
> +                }.toNot(throwError())
One more thing: could you add some `to(equal())` evaluation please?

2024-01-05 04:49 UTC, superarts commented on StringCatalogEnum/Tests/StringCatalogEnumTests/StringCatalogEnumTests.swift
> +                """
And here.

2024-01-05 05:12 UTC, superarts approved these changes

2024-01-05 05:12 UTC, superarts commented on StringCatalogEnum/Tests/StringCatalogEnumTests/StringCatalogEnumTests.swift
> +                    expect(decodedData.strings["Login"]?.localizations?["en"]?.stringUnit?.state).to(equal("translated"))
Eventually we want to use `Decodable` for all these JSON objects, but this PR is good as is.

2024-01-05 05:13 UTC, merged